#!/usr/bin/env python3
"""Regenerate the Strategies section of README.md from the replication catalogue.

Reads the Strategies-NAV dataset on Hugging Face, measures each replication over
its own active window, keeps the ones that clear a t-statistic of 1.96, and
writes one table per asset class between the STRATEGIES markers in README.md.

    HF_ACCESS_TOKEN=... python scripts/build_strategies_table.py

The point of generating rather than hand-maintaining is that the numbers move
when the catalogue does, so the section cannot quietly go stale.
"""
import os
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
START = "<!-- STRATEGIES:START - generated by scripts/build_strategies_table.py -->"
END = "<!-- STRATEGIES:END -->"
TOP_N = 12
MIN_YEARS = 10
# A replicated NAV can degenerate: a series that never moves, or one that doubles
# every month. Both produce meaningless ratios, so they are excluded outright.
MIN_VOLATILITY = 0.01
MAX_VOLATILITY = 1.00

ASSET_ORDER = [
    ("Equities", ("Equities",)),
    ("Bonds", ("Bonds",)),
    ("Commodities", ("Commodities",)),
    ("Currencies", ("Currencies", "Forex")),
    ("Cryptocurrencies", ("Cryptocurrencies",)),
    ("Derivatives", ("Derivatives",)),
    ("Multi-asset", ()),
]

# Paper titles stay in the language they were published in, since they are
# citations. Everything the generator writes around them is translated, so the
# Chinese README does not end up an English one with a Chinese preamble.
LOCALES = {
    "README.md": {
        "buckets": {label: label for label, _ in ASSET_ORDER},
        "header": "| Strategy | Sharpe | t-stat | Volatility | Years tested |",
        "caveat": (
            "*Showing the {shown} strongest of {pool:,} replications that clear a t-statistic "
            "of 1.96 over at least {years} years, up to {top} per asset class. Sharpe ratios "
            "are measured on each strategy's own active window, not on a common calendar, and "
            "are gross of trading costs. Series with an annualised volatility outside 1% to "
            "100% are treated as degenerate and dropped. The t-statistic is shown because a "
            "Sharpe ratio without one says very little: half the catalogue does not clear it.*"
        ),
    },
    "README_ja.md": {
        "buckets": {
            "Equities": "株式",
            "Bonds": "債券",
            "Commodities": "コモディティ",
            "Currencies": "通貨",
            "Cryptocurrencies": "暗号資産",
            "Derivatives": "デリバティブ",
            "Multi-asset": "マルチアセット",
        },
        "header": "| 戦略 | シャープレシオ | t 値 | ボラティリティ | 検証年数 |",
        "caveat": (
            "*少なくとも {years} 年の期間で t 値 1.96 を超えた {pool:,} 件の複製のうち、"
            "上位 {shown} 件を資産クラスごとに最大 {top} 件まで掲載しています。シャープレシオは"
            "共通のカレンダーではなく各戦略自身の稼働期間で計測しており、取引コストは差し引いて"
            "いません。年率ボラティリティが 1% から 100% の範囲外の系列は異常値として除外して"
            "います。t 値を併記するのは、それを伴わないシャープレシオがほとんど何も語らない"
            "ためです。カタログの半数はこの水準に届きません。*"
        ),
    },
    "README_zh.md": {
        "buckets": {
            "Equities": "股票",
            "Bonds": "债券",
            "Commodities": "大宗商品",
            "Currencies": "外汇",
            "Cryptocurrencies": "加密货币",
            "Derivatives": "衍生品",
            "Multi-asset": "多资产",
        },
        "header": "| 策略 | 夏普比率 | t 统计量 | 波动率 | 测试年数 |",
        "caveat": (
            "*在 {pool:,} 个复现结果中，展示最强的 {shown} 个，每类资产最多 {top} 个。入选条件是"
            "在至少 {years} 年的窗口上 t 统计量超过 1.96。夏普比率在每个策略自身的活跃窗口上计算，"
            "而非统一日历，且未扣除交易成本。年化波动率不在 1% 至 100% 区间内的序列视为异常并剔除。"
            "之所以同时给出 t 统计量，是因为脱离它的夏普比率意义有限：目录中有一半达不到这个门槛。*"
        ),
    },
}


def active_window(values: np.ndarray) -> np.ndarray:
    """Trim the padded flat prefix and suffix a NAV series can carry."""
    returns = pd.Series(values).pct_change().fillna(0).to_numpy()
    moved = np.nonzero(returns != 0)[0]
    if len(moved) < 2:
        return values[:0]
    return values[max(moved[0] - 1, 0) : moved[-1] + 1]


def measure(nav: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for slug, group in nav.groupby("slug", sort=False):
        group = group.sort_values("date")
        values = active_window(group["value"].to_numpy(dtype=float))
        if len(values) < 252:
            continue
        returns = pd.Series(values).pct_change().dropna()
        if returns.std() == 0:
            continue
        years = len(returns) / 252.0
        sharpe = returns.mean() / returns.std() * np.sqrt(252)
        rows.append(
            {
                "slug": slug,
                "sharpe": sharpe,
                "years": years,
                "t": sharpe * np.sqrt(years),
                "volatility": returns.std() * np.sqrt(252),
            }
        )
    return pd.DataFrame(rows)


def clean_title(title: str) -> str:
    """Papers are stored with their own capitalisation, some of it shouted."""
    letters = [c for c in title if c.isalpha()]
    if letters and sum(c.isupper() for c in letters) / len(letters) > 0.7:
        title = title.title()
    return title.replace("|", "/")


def asset_bucket(markets: str) -> str:
    parts = {p.strip() for p in (markets or "").split(",") if p.strip()}
    if not parts:
        return ""
    if len(parts) > 1:
        return "Multi-asset"
    for label, names in ASSET_ORDER:
        if parts & set(names):
            return label
    return ""


def render(table: pd.DataFrame, locale: dict) -> tuple[str, int]:
    blocks, shown = [], 0
    for label, _ in ASSET_ORDER:
        rows = table[table["bucket"] == label].nlargest(TOP_N, "sharpe")
        if rows.empty:
            continue
        shown += len(rows)
        blocks += [
            f"## {locale['buckets'][label]}",
            "",
            locale["header"],
            "|---|---|---|---|---|",
        ]
        for row in rows.itertuples():
            url = f"https://paperswithbacktest.com/strategies/{row.slug}"
            blocks.append(
                f"| [{row.title}]({url}) | `{row.sharpe:.2f}` | `{row.t:.1f}` | "
                f"`{row.volatility * 100:.1f}%` | `{row.years:.0f}` |"
            )
        blocks.append("")

    caveat = locale["caveat"].format(
        shown=shown, pool=len(table), years=MIN_YEARS, top=TOP_N
    )
    return "\n".join([START, "", caveat, ""] + blocks + [END]), shown


def main() -> int:
    token = os.environ.get("HF_ACCESS_TOKEN")
    if not token:
        print("HF_ACCESS_TOKEN is required", file=sys.stderr)
        return 1

    from huggingface_hub import HfApi, hf_hub_download

    api = HfApi(token=token)
    files = [
        f
        for f in api.list_repo_files(
            "paperswithbacktest/Strategies-NAV", repo_type="dataset", token=token
        )
        if f.endswith(".parquet")
    ]
    measured = []
    for name in files:
        path = hf_hub_download(
            "paperswithbacktest/Strategies-NAV", name, repo_type="dataset", token=token
        )
        measured.append(measure(pd.read_parquet(path)))
        print(f"  measured {name}", file=sys.stderr)
    table = pd.concat(measured, ignore_index=True)

    meta = pd.read_json("scripts/paper_meta.json").T
    meta.index = [i.replace("_", "-") for i in meta.index]
    table["title"] = [clean_title(meta["title"].get(s, "")) for s in table["slug"]]
    table["bucket"] = [asset_bucket(meta["markets"].get(s, "")) for s in table["slug"]]

    table = table[
        (table["t"] > 1.96)
        & (table["years"] >= MIN_YEARS)
        & (table["volatility"] >= MIN_VOLATILITY)
        & (table["volatility"] <= MAX_VOLATILITY)
        & (table["title"] != "")
        & (table["bucket"] != "")
    ]

    shown = 0
    for name, locale in LOCALES.items():
        readme = ROOT / name
        text = readme.read_text()
        if START not in text:
            print(f"markers not found in {name}", file=sys.stderr)
            return 1
        body, shown = render(table, locale)
        readme.write_text(
            re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: body, text, flags=re.S)
        )
    print(f"wrote {shown} rows into {len(LOCALES)} READMEs, "
          f"the strongest of {len(table):,} replications "
          f"across {table['bucket'].nunique()} asset classes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
