#!/usr/bin/env python3
"""Regenerate the Strategies section of README.md from the replication catalogue.

Reads the Strategies-NAV dataset on Hugging Face, measures each replication over
its own active window, keeps the ones that clear a t-statistic of 1.96, and
writes one table per asset class between the STRATEGIES markers in README.md.

    HF_ACCESS_TOKEN=... python scripts/build_strategies_table.py

The point of generating rather than hand-maintaining is that the numbers move
when the catalogue does, so the section cannot quietly go stale.
"""
import os
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
READMES = [ROOT / "README.md", ROOT / "README_zh.md"]
START = "<!-- STRATEGIES:START - generated by scripts/build_strategies_table.py -->"
END = "<!-- STRATEGIES:END -->"
TOP_N = 12
MIN_YEARS = 10
# A replicated NAV can degenerate: a series that never moves, or one that doubles
# every month. Both produce meaningless ratios, so they are excluded outright.
MIN_VOLATILITY = 0.01
MAX_VOLATILITY = 1.00

ASSET_ORDER = [
    ("Equities", ("Equities",)),
    ("Bonds", ("Bonds",)),
    ("Commodities", ("Commodities",)),
    ("Currencies", ("Currencies", "Forex")),
    ("Cryptocurrencies", ("Cryptocurrencies",)),
    ("Derivatives", ("Derivatives",)),
    ("Multi-asset", ()),
]


def active_window(values: np.ndarray) -> np.ndarray:
    """Trim the padded flat prefix and suffix a NAV series can carry."""
    returns = pd.Series(values).pct_change().fillna(0).to_numpy()
    moved = np.nonzero(returns != 0)[0]
    if len(moved) < 2:
        return values[:0]
    return values[max(moved[0] - 1, 0) : moved[-1] + 1]


def measure(nav: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for slug, group in nav.groupby("slug", sort=False):
        group = group.sort_values("date")
        values = active_window(group["value"].to_numpy(dtype=float))
        if len(values) < 252:
            continue
        returns = pd.Series(values).pct_change().dropna()
        if returns.std() == 0:
            continue
        years = len(returns) / 252.0
        sharpe = returns.mean() / returns.std() * np.sqrt(252)
        rows.append(
            {
                "slug": slug,
                "sharpe": sharpe,
                "years": years,
                "t": sharpe * np.sqrt(years),
                "volatility": returns.std() * np.sqrt(252),
            }
        )
    return pd.DataFrame(rows)


def clean_title(title: str) -> str:
    """Papers are stored with their own capitalisation, some of it shouted."""
    letters = [c for c in title if c.isalpha()]
    if letters and sum(c.isupper() for c in letters) / len(letters) > 0.7:
        title = title.title()
    return title.replace("|", "/")


def asset_bucket(markets: str) -> str:
    parts = {p.strip() for p in (markets or "").split(",") if p.strip()}
    if not parts:
        return ""
    if len(parts) > 1:
        return "Multi-asset"
    for label, names in ASSET_ORDER:
        if parts & set(names):
            return label
    return ""


def render(table: pd.DataFrame) -> str:
    lines = [
        START,
        "",
        f"*Generated from {len(table):,} replications that clear a t-statistic of 1.96 over at "
        f"least {MIN_YEARS} years. Sharpe ratios are measured on each strategy's own active "
        "window, not on a common calendar, and are gross of trading costs. Series with an "
        "annualised volatility outside 1% to 100% are treated as degenerate and dropped. "
        "The t-statistic is "
        "shown because a Sharpe ratio without one says very little: half the catalogue does not "
        "clear it.*",
        "",
    ]
    for label, _ in ASSET_ORDER:
        block = table[table["bucket"] == label].nlargest(TOP_N, "sharpe")
        if block.empty:
            continue
        lines += [
            f"## {label}",
            "",
            "| Strategy | Sharpe | t-stat | Volatility | Years tested |",
            "|---|---|---|---|---|",
        ]
        for row in block.itertuples():
            url = f"https://paperswithbacktest.com/strategies/{row.slug}"
            lines.append(
                f"| [{row.title}]({url}) | `{row.sharpe:.2f}` | `{row.t:.1f}` | "
                f"`{row.volatility * 100:.1f}%` | `{row.years:.0f}` |"
            )
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    token = os.environ.get("HF_ACCESS_TOKEN")
    if not token:
        print("HF_ACCESS_TOKEN is required", file=sys.stderr)
        return 1

    from huggingface_hub import HfApi, hf_hub_download

    api = HfApi(token=token)
    files = [
        f
        for f in api.list_repo_files(
            "paperswithbacktest/Strategies-NAV", repo_type="dataset", token=token
        )
        if f.endswith(".parquet")
    ]
    measured = []
    for name in files:
        path = hf_hub_download(
            "paperswithbacktest/Strategies-NAV", name, repo_type="dataset", token=token
        )
        measured.append(measure(pd.read_parquet(path)))
        print(f"  measured {name}", file=sys.stderr)
    table = pd.concat(measured, ignore_index=True)

    meta = pd.read_json("scripts/paper_meta.json").T
    meta.index = [i.replace("_", "-") for i in meta.index]
    table["title"] = [clean_title(meta["title"].get(s, "")) for s in table["slug"]]
    table["bucket"] = [asset_bucket(meta["markets"].get(s, "")) for s in table["slug"]]

    table = table[
        (table["t"] > 1.96)
        & (table["years"] >= MIN_YEARS)
        & (table["volatility"] >= MIN_VOLATILITY)
        & (table["volatility"] <= MAX_VOLATILITY)
        & (table["title"] != "")
        & (table["bucket"] != "")
    ]

    body = render(table)
    for readme in READMES:
        text = readme.read_text()
        if START not in text:
            print(f"markers not found in {readme.name}", file=sys.stderr)
            return 1
        readme.write_text(
            re.sub(re.escape(START) + r".*?" + re.escape(END), body, text, flags=re.S)
        )
    print(f"wrote {len(table):,} strategies across {table['bucket'].nunique()} buckets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
